name: Build unified adlist

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Compute tag
        id: meta
        run: echo "tag=daily-$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"

      - name: Build lists
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p build tmp
          : > tmp/raw.txt

          if [ ! -f sources.txt ]; then
            echo "ERROR: falta sources.txt en la raíz del repo." >&2
            exit 1
          fi

          while read -r u; do
            [ -z "${u:-}" ] && continue
            curl -fsSL "$u" >> tmp/raw.txt || true
            echo >> tmp/raw.txt
          done < sources.txt

          cat tmp/raw.txt \
            | tr -d '\r' \
            | sed -E 's/[[:space:]]+#.*$//' \
            | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//' \
            | awk 'NF' \
            | sed -E 's#^\|\|([^/\^]+)\^.*$#\1#' \
            | sed -E 's#^https?://([^/]+).*#\1#' \
            | sed -E 's/^(0\.0\.0\.0|127\.0\.0\.1)[[:space:]]+//; s/^www\.//' \
            | sed -E 's/^\.+//' \
            | tr A-Z a-z \
            | sort -u > build/domains.txt

          # Artefactos por sistema
          awk '{print "||"$1"^"}' build/domains.txt > build/unified-adblock.txt
          cp build/unified-adblock.txt build/unified-adguard.txt
          cp build/domains.txt build/technitium-domains.txt
          awk '{print "0.0.0.0 "$1}' build/domains.txt > build/technitium-hosts.txt
          awk '{print "0.0.0.0 "$1}' build/domains.txt > build/pihole-hosts.txt
          awk '{print "address=/"$1"/0.0.0.0"}' build/domains.txt > build/dnsmasq.conf
          awk '{print "local-zone: \""$1"\" always_nxdomain"}' build/domains.txt > build/unbound.conf

          # Página principal sin heredoc (evita errores YAML)
          rm -f build/index.html
          echo '<!doctype html>' >> build/index.html
          echo '<html lang="es"><head><meta charset="utf-8"><title>Mikrotik Adlists — Blocklists Unificadas</title><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:sans-serif;max-width:900px;margin:2rem auto;line-height:1.6;padding:0 1rem}code,pre{background:#f4f4f4;padding:.2rem .4rem;border-radius:4px}a{color:#0056b3;text-decoration:none}a:hover{text-decoration:underline}footer{margin-top:2rem;font-size:.9em;color:#555}</style></head><body>' >> build/index.html
          echo '<h1>🧱 mikrotik-adlists</h1>' >> build/index.html
          echo '<p>Listas unificadas (AdBlock, AdGuard, Technitium, Pi-hole, dnsmasq, Unbound)</p>' >> build/index.html
          echo '<ul>' >> build/index.html
          echo '<li><a href="unified-adblock.txt">AdBlock / uBlock</a></li>' >> build/index.html
          echo '<li><a href="unified-adguard.txt">AdGuard</a></li>' >> build/index.html
          echo '<li><a href="technitium-domains.txt">Technitium dominios</a></li>' >> build/index.html
          echo '<li><a href="technitium-hosts.txt">Technitium hosts</a></li>' >> build/index.html
          echo '<li><a href="pihole-hosts.txt">Pi-hole</a></li>' >> build/index.html
          echo '<li><a href="dnsmasq.conf">dnsmasq</a></li>' >> build/index.html
          echo '<li><a href="unbound.conf">Unbound</a></li>' >> build/index.html
          echo '<li><a href="domains.txt">Dominios base</a></li>' >> build/index.html
          echo '<li><a href="SHA256SUMS">SHA256SUMS</a></li>' >> build/index.html
          echo '</ul>' >> build/index.html
          echo '<footer>© 2025 Carlos Dagorret — dagorret.com.ar</footer>' >> build/index.html
          echo '</body></html>' >> build/index.html

          # Checksums
          (cd build && sha256sum domains.txt unified-adblock.txt unified-adguard.txt technitium-domains.txt technitium-hosts.txt pihole-hosts.txt dnsmasq.conf unbound.conf > SHA256SUMS)

      - name: Commit artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add build/
          git commit -m "Daily build" || echo "No changes"
          git push

      - uses: actions/upload-pages-artifact@v3
        with:
          path: build

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build.outputs.tag }}
          name: "Daily build ${{ needs.build.outputs.tag }}"
          files: |
            build/domains.txt
            build/unified-adblock.txt
            build/unified-adguard.txt
            build/technitium-domains.txt
            build/technitium-hosts.txt
            build/pihole-hosts.txt
            build/dnsmasq.conf
            build/unbound.conf
            build/SHA256SUMS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_pages:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
